[Path]
Ruta = "C:\Archivos de programa\SGPADM\"

[Base_de_datos]
Mdb = "dbgtadm.mdb"

[Gif]
Ruta = "C:\Archivos de programa\SGPADM\"

[Provider]
Jet = "Microsoft.Jet.OLEDB.4.0"

[SQL SERVER]
Servidor = CECLCES-SASQL02
DataBase = ®­³Á“
Usuario  = ½¬¿´¾
Password = Š¾o´r¿uƒ‚„†

;Servidor = 10.56.71.22
;DataBase = ®­³Á“
;Usuario  = ½²¼
;Password = ½²¼·¾½

[ORACLE]
Servidor = Œ¢
Usuario  = ˜œ ”
Password = ½²¼·¾½


