[Path]
Ruta = "C:\Archivos de programa\SGPADM\"

[Base_de_datos]
Mdb = "dbgtadm.mdb"

[Gif]
Ruta = "C:\Archivos de programa\SGPADM\"

[Provider]
Jet = "Microsoft.Jet.OLEDB.4.0"

[SQL SERVER]

:Servidor = CECLCES-SASQL21(Ambiente QAS)
Servidor = 10.55.96.26
:Servidor = CECLCES-AZSQL02
:Servidor = CECLCES-AZSQL02
DataBase = ®­³Á“
Usuario  = ½¬¿´¾
Password = Š¾o´r¿uƒ‚„†

:Servidor = CECLCES-SASQL02(Ambiente Producción)
;Servidor = 10.55.65.17
;DataBase = ®­³Á“
;Usuario  = ½¬¿´¾
;Password = Š¾o´r¿uƒ‚„†


[ORACLE]
Servidor = Œ¢
Usuario  = ˜œ ”
Password = ½²¼·¾½


